import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { app, BrowserWindow, dialog, ipcMain, Notification, shell } from 'electron'
import electronUpdater from 'electron-updater'
import { createUpdatePrompt } from './updatePrompt.js'

// electron-updater is CommonJS. Import its default namespace explicitly so
// Electron's native ESM loader does not rely on synthetic named exports.
const { autoUpdater } = electronUpdater

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const isDevelopment = process.env.QIVO_DESKTOP_DEV === '1' || !app.isPackaged
if (process.platform === 'linux') app.setDesktopName('io.qivo.desktop')
if (process.platform === 'win32') app.setAppUserModelId('io.qivo.desktop')
const configuredURL = process.env.QIVO_DESKTOP_URL?.trim()
const defaultURL = isDevelopment ? 'http://localhost:5199/app' : 'https://qivo.io/app'
const appURL = new URL(configuredURL || defaultURL)

if (!['http:', 'https:'].includes(appURL.protocol)) {
  throw new Error('QIVO_DESKTOP_URL must use http or https')
}

const trustedHosts = new Set(['qivo.io', 'www.qivo.io', 'localhost'])
const trustedSuffixes = ['.qivo.io']
const oauthHosts = new Set(['accounts.google.com', 'login.microsoftonline.com', 'login.live.com'])

function isTrustedHost(hostname: string): boolean {
  const host = hostname.toLowerCase()
  return trustedHosts.has(host) || trustedSuffixes.some((suffix) => host.endsWith(suffix))
}

function isAllowedURL(rawURL: string, allowOAuth = false): boolean {
  let parsed: URL
  try {
    parsed = new URL(rawURL)
  } catch {
    return false
  }
  if (parsed.protocol === 'http:' && parsed.hostname !== 'localhost') return false
  if (!['http:', 'https:'].includes(parsed.protocol)) return false
  // Only the configured app origin stays in the renderer. Convex endpoints
  // and links to other Qivo subdomains open externally instead of becoming a
  // new top-level renderer document.
  if (parsed.origin === appURL.origin) return true
  return allowOAuth && parsed.protocol === 'https:' && oauthHosts.has(parsed.hostname.toLowerCase())
}

if (
  appURL.username ||
  appURL.password ||
  appURL.search ||
  appURL.hash ||
  !isTrustedHost(appURL.hostname) ||
  (appURL.protocol === 'http:' && appURL.hostname !== 'localhost')
) {
  throw new Error('QIVO_DESKTOP_URL must be a trusted Qivo HTTPS origin or localhost HTTP origin')
}

let mainWindow: BrowserWindow | null = null
let pendingDeepLink: string | null = null
let pendingOAuth: { state: string; expiresAt: number } | null = null

type UpdateStatus =
  | 'idle'
  | 'checking'
  | 'available'
  | 'downloading'
  | 'downloaded'
  | 'not-available'
  | 'error'

type UpdateState = {
  status: UpdateStatus
  version?: string
  message?: string
  blocked: boolean
}

let updateState: UpdateState = { status: 'idle', blocked: false }
let updaterReady = false

function isAuthorizedRenderer(event: {
  sender: Electron.WebContents
  senderFrame: Electron.WebFrameMain | null
}): boolean {
  if (event.sender !== mainWindow?.webContents || !event.senderFrame) return false
  try {
    return new URL(event.senderFrame.url).origin === appURL.origin
  } catch {
    return false
  }
}

function sendUpdateState(): void {
  mainWindow?.webContents.send('qivo:updates:state', updateState)
}

function setUpdateState(next: Partial<UpdateState>): UpdateState {
  updateState = { ...updateState, ...next }
  sendUpdateState()
  return updateState
}

const updatePrompt = createUpdatePrompt({
  isAvailable: () =>
    Boolean(mainWindow && !mainWindow.isDestroyed() && updateState.status === 'downloaded'),
  isBlocked: () => updateState.blocked,
  confirmInstall: async () => {
    if (!mainWindow || mainWindow.isDestroyed()) return false
    const answer = await dialog.showMessageBox(mainWindow, {
      type: 'info',
      buttons: ['Restart and update', 'Later'],
      defaultId: 0,
      cancelId: 1,
      title: 'Update Qivo',
      message: 'A new version of Qivo is ready.',
      detail: 'Qivo will restart to finish installing the update.',
    })
    return answer.response === 0
  },
  install: () => autoUpdater.quitAndInstall(false, true),
  showNotification: (version, onClick) => {
    if (!Notification.isSupported()) return false
    const notification = new Notification({
      title: 'Qivo update ready',
      body: `Qivo ${version} is ready to install.`,
    })
    notification.on('click', onClick)
    notification.show()
    return true
  },
})

function setupAutoUpdates(): void {
  // electron-updater needs an app-update.yml generated by electron-builder.
  // Never contact a feed while running from source; this keeps local development
  // and browser smoke drives deterministic.
  if (!app.isPackaged || process.env.QIVO_DISABLE_UPDATES === '1') return
  const feedURL = process.env.QIVO_DESKTOP_UPDATE_URL?.trim()
  // A local package build deliberately has no updater configuration. Do not
  // turn that normal case into a noisy "latest.yml not found" error.
  if (!feedURL && !fs.existsSync(path.join(process.resourcesPath, 'app-update.yml'))) return
  if (feedURL) {
    try {
      const parsed = new URL(feedURL)
      if (
        parsed.protocol !== 'https:' ||
        parsed.username ||
        parsed.password ||
        parsed.search ||
        parsed.hash
      )
        throw new Error('update URL must be HTTPS without credentials, query, or hash')
      autoUpdater.setFeedURL({ provider: 'generic', url: parsed.href })
    } catch (error) {
      setUpdateState({
        status: 'error',
        message: error instanceof Error ? error.message : String(error),
      })
      return
    }
  }
  autoUpdater.autoDownload = true
  // Download in the background and finish on a normal app quit. A click on
  // the ready notification still offers an immediate, confirmed restart.
  // Linux .deb/.rpm updates invoke a privileged package manager. Only install
  // those after the explicit confirmation above; Windows and macOS can finish
  // their downloaded installer on a normal quit.
  autoUpdater.autoInstallOnAppQuit = process.platform !== 'linux'
  updaterReady = true
  autoUpdater.on('checking-for-update', () =>
    setUpdateState({ status: 'checking', message: undefined }),
  )
  autoUpdater.on('update-available', (info) =>
    setUpdateState({ status: 'available', version: info.version, message: undefined }),
  )
  autoUpdater.on('download-progress', () => setUpdateState({ status: 'downloading' }))
  autoUpdater.on('update-not-available', () => setUpdateState({ status: 'not-available' }))
  autoUpdater.on('update-downloaded', (info) => {
    setUpdateState({ status: 'downloaded', version: info.version, message: undefined })
    updatePrompt.notify(info.version)
  })
  autoUpdater.on('error', (error) =>
    setUpdateState({
      status: 'error',
      message: error instanceof Error ? error.message : String(error),
    }),
  )
  // A failed check is transient (offline starts are common), so the shell
  // reports it to its update UI and carries on with the already-installed app.
  void autoUpdater.checkForUpdates().catch((error: unknown) => {
    setUpdateState({
      status: 'error',
      message: error instanceof Error ? error.message : String(error),
    })
  })
  // Keep a running desktop session current without interrupting it. The
  // updater downloads in the background and the install path still requires
  // the same safety lease and explicit restart confirmation.
  setInterval(
    () => {
      if (updateState.status === 'downloaded' || updateState.status === 'downloading') return
      void autoUpdater.checkForUpdates().catch(() => {
        // Offline checks are expected; the next interval retries.
      })
    },
    4 * 60 * 60 * 1000,
  )
}

function showNotification(payload: unknown): boolean {
  if (!payload || typeof payload !== 'object') return false
  const value = payload as Record<string, unknown>
  const tag = typeof value.tag === 'string' ? value.tag.slice(0, 256) : ''
  const title = typeof value.title === 'string' ? value.title.slice(0, 256) : ''
  const body = typeof value.body === 'string' ? value.body.slice(0, 4_096) : ''
  if (!tag || !title) return false
  if (!Notification.isSupported()) return false
  try {
    const notification = new Notification({ title, body, silent: false })
    notification.on('click', () => {
      if (!mainWindow || mainWindow.isDestroyed()) return
      if (mainWindow.isMinimized()) mainWindow.restore()
      mainWindow.show()
      mainWindow.focus()
      mainWindow.webContents.send('qivo:notifications:click', tag)
    })
    notification.show()
    return true
  } catch {
    return false
  }
}

function notificationPermission(): 'default' | 'granted' | 'denied' | 'unsupported' {
  return Notification.isSupported() ? 'granted' : 'unsupported'
}

function parseOAuthCallback(
  rawURL: string,
): { state: string; ott?: string; error?: string } | null {
  let parsed: URL
  try {
    parsed = new URL(rawURL)
  } catch {
    return null
  }
  if (parsed.protocol !== 'qivo:' || parsed.hostname !== 'auth') return null
  const state = parsed.searchParams.get('state') || ''
  if (!/^[a-zA-Z0-9_-]{32,128}$/.test(state)) return null
  const ott = parsed.searchParams.get('ott') || undefined
  const error = parsed.searchParams.get('error') || undefined
  if (!ott && !error) return null
  if (ott && !/^[a-zA-Z0-9._~-]{8,2048}$/.test(ott)) return null
  if (error && !/^[A-Z0-9_:-]{1,128}$/i.test(error)) return null
  return { state, ...(ott ? { ott } : {}), ...(error ? { error } : {}) }
}

function consumeDeepLink(rawURL: string): void {
  const callback = parseOAuthCallback(rawURL)
  if (!callback || !pendingOAuth || pendingOAuth.expiresAt < Date.now()) return
  if (callback.state !== pendingOAuth.state) return
  pendingOAuth = null
  const target = new URL(appURL.href)
  target.pathname = target.pathname.replace(/\/$/, '') || '/app'
  if (callback.ott) target.searchParams.set('ott', callback.ott)
  if (callback.error) target.searchParams.set('error', callback.error)
  target.searchParams.delete('desktop_auth')
  if (mainWindow && !mainWindow.isDestroyed()) {
    void mainWindow.loadURL(target.href)
    mainWindow.show()
    mainWindow.focus()
  } else {
    pendingDeepLink = target.href
  }
}

function registerProtocol(): void {
  if (process.platform !== 'win32' && process.platform !== 'darwin' && process.platform !== 'linux')
    return
  if (process.defaultApp) {
    // Electron's development launcher needs the script path in the registration.
    app.setAsDefaultProtocolClient('qivo', process.execPath, [path.resolve(process.argv[1] || '')])
  } else {
    app.setAsDefaultProtocolClient('qivo')
  }
}

function createWindow(): void {
  mainWindow = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 960,
    minHeight: 640,
    backgroundColor: '#111113',
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  })
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^(mailto:|tel:)/i.test(url)) {
      void shell.openExternal(url)
      return { action: 'deny' }
    }
    if (/^https?:\/\//i.test(url) && !isAllowedURL(url)) void shell.openExternal(url)
    return { action: 'deny' }
  })
  mainWindow.webContents.on('will-navigate', (event, url) => {
    if (isAllowedURL(url, true)) return
    event.preventDefault()
    if (/^(https?:\/\/|mailto:|tel:)/i.test(url)) void shell.openExternal(url)
  })
  mainWindow.on('closed', () => {
    mainWindow = null
  })
  void mainWindow.loadURL(appURL.href)
  if (pendingDeepLink) {
    const target = pendingDeepLink
    pendingDeepLink = null
    void mainWindow.loadURL(target)
  }
}

function installIPC(): void {
  ipcMain.on('qivo:notifications:permission', (event) => {
    if (!isAuthorizedRenderer(event)) return
    event.returnValue = notificationPermission()
  })
  ipcMain.handle('qivo:notifications:request-permission', (event) => {
    if (!isAuthorizedRenderer(event)) return 'denied'
    return notificationPermission()
  })
  ipcMain.handle('qivo:notifications:show', (event, payload: unknown) => {
    if (!isAuthorizedRenderer(event)) return false
    return showNotification(payload)
  })
  ipcMain.handle('qivo:updates:get-state', (event) => {
    if (!isAuthorizedRenderer(event))
      return { status: 'error', message: 'unauthorized', blocked: true }
    return updateState
  })
  ipcMain.handle('qivo:updates:check', async (event) => {
    if (!isAuthorizedRenderer(event) || !updaterReady) return updateState
    setUpdateState({ status: 'checking', message: undefined })
    try {
      await autoUpdater.checkForUpdates()
    } catch (error) {
      setUpdateState({
        status: 'error',
        message: error instanceof Error ? error.message : String(error),
      })
    }
    return updateState
  })
  ipcMain.handle('qivo:updates:install', async (event) => {
    if (!isAuthorizedRenderer(event) || !updaterReady || updateState.blocked) return false
    return updatePrompt.install()
  })
  ipcMain.on('qivo:updates:set-blocked', (event, value: unknown) => {
    if (!isAuthorizedRenderer(event) || typeof value !== 'boolean') return
    const wasBlocked = updateState.blocked
    setUpdateState({ blocked: value })
    if (wasBlocked && !value && updateState.status === 'downloaded' && updateState.version)
      updatePrompt.notify(updateState.version)
  })
  ipcMain.handle('qivo:auth:begin-oauth', (event) => {
    if (!isAuthorizedRenderer(event)) throw new Error('unauthorized')
    const state = crypto.randomBytes(32).toString('base64url')
    pendingOAuth = { state, expiresAt: Date.now() + 10 * 60_000 }
    const callback = new URL(appURL.href)
    callback.search = ''
    callback.pathname = callback.pathname.replace(/\/$/, '') || '/app'
    callback.searchParams.set('desktop_auth', state)
    return { callbackURL: callback.href }
  })
  ipcMain.handle('qivo:auth:open-oauth', (event, rawURL: unknown) => {
    if (!isAuthorizedRenderer(event) || typeof rawURL !== 'string') return false
    if (!isAllowedURL(rawURL, true)) return false
    // Keep provider sign-in in the system browser. The registered qivo://
    // protocol returns the one-time result to this shell after the callback.
    const provider = new URL(rawURL)
    if (!oauthHosts.has(provider.hostname.toLowerCase())) return false
    void shell.openExternal(provider.href)
    return true
  })
}

const gotLock = app.requestSingleInstanceLock()
if (!gotLock) {
  app.quit()
} else {
  app.on('second-instance', (_event, commandLine) => {
    const deepLink = commandLine.find((arg) => arg.startsWith('qivo://'))
    if (deepLink) consumeDeepLink(deepLink)
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore()
      mainWindow.show()
      mainWindow.focus()
    }
  })
  app.on('open-url', (event, url) => {
    event.preventDefault()
    consumeDeepLink(url)
  })
  void app.whenReady().then(() => {
    registerProtocol()
    installIPC()
    createWindow()
    setupAutoUpdates()
    const startupDeepLink = process.argv.find((arg) => arg.startsWith('qivo://'))
    if (startupDeepLink) consumeDeepLink(startupDeepLink)
    app.on('activate', () => {
      if (!mainWindow) createWindow()
    })
  })
  app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit()
  })
}
